# Generated by Django 3.1.6 on 2021-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=20, verbose_name="User's name")),
                ('Password', models.CharField(max_length=30, verbose_name='User password')),
                ('courses', models.ManyToManyField(to='Courses.Course')),
            ],
        ),
    ]
