# Generated by Django 3.1.6 on 2021-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='Login',
            field=models.CharField(max_length=20, unique=True, verbose_name="User's name"),
        ),
    ]
