# Generated by Django 3.1.6 on 2021-04-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Status',
            field=models.CharField(choices=[('AC', 'active'), ('IA', 'inactive'), ('MO', 'modifying')], default='AC', max_length=2, verbose_name='Status'),
        ),
    ]
