# Generated by Django 3.1.6 on 2021-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20210427_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='Action',
            field=models.BooleanField(default=False, verbose_name='Created'),
        ),
    ]
